# Generated by Django 3.0.7 on 2020-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hight_in_cm',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wight_in_kg',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
